name: Commit Build

on:
  push:
    branches: 
      - '**'
    tags-ignore:
      - '**'

jobs:
  buildLinux:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Get Commit Ref
        run: |
          COMMIT_REF=$(git rev-parse --short $GITHUB_SHA)
          echo "COMMIT_REF: $COMMIT_REF"
          echo "COMMIT_REF=$COMMIT_REF" >>$GITHUB_ENV

      - name: Build
        run: |
          export TZ='America/Los_Angeles'
          sudo apt-get install srecord
          make distlog
          rm -rf .git*

      - name: List Output
        run: |
          cd Binary
          ls -l
          find -type f -exec md5sum '{}' \;

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.0
        with:
          name: RomWBW-${{env.COMMIT_REF}}-Linux
          path: .

      - name: Build Docs
        run: |
          export TZ='America/Los_Angeles'
          sudo apt-get install gpp pandoc
          pip install mkdocs
          make -C Source/Doc deploy_mkdocs
          mkdocs build -f Source/Doc/mkdocs.yml

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Source/Doc/site

  buildMacOS:
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Get Commit Ref
        run: |
          COMMIT_REF=$(git rev-parse --short $GITHUB_SHA)
          echo "COMMIT_REF: $COMMIT_REF"
          echo "COMMIT_REF=$COMMIT_REF" >>$GITHUB_ENV

      - name: Build
        run: |
          export TZ='America/Los_Angeles'
          brew install srecord
          make distlog
          rm -rf .git*

      - name: List Output
        run: |
          cd Binary
          ls -l
          find . -type f -exec md5 -r -- '{}' +;

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.0
        with:
          name: RomWBW-${{env.COMMIT_REF}}-MacOS
          path: .
